// src/App.svelte
<script>
  const annotation =
    "サンタクロースはなんでもあげれる訳ではありません。プレゼントはお父さん・お母さんと相談して、お二人が「いいよ」と言ったものを入力してください。";
</script>

<main>
  <section class="hero">
    <h1>サンタさんへのおねがいフォーム</h1>
    <p>がんばったこと、うれしかったことを教えてね。iPadでも見やすい大きめの文字だよ。</p>
  </section>

  <section class="card">
    <form name="santa-request" method="POST" data-netlify="true" action="/success" netlify-honeypot="bot-field">
      <input type="hidden" name="form-name" value="santa-request" />
      <p class="honeypot">
        <label>
          ロボットチェック
          <input name="bot-field" />
        </label>
      </p>

      <label>
        欲しいプレゼント
        <span class="note">{annotation}</span>
        <input
          type="text"
          name="present"
          aria-describedby="present-note"
          placeholder="例：やさしい絵本、ぬいぐるみなど"
          required
        />
      </label>

      <label>
        今年がんばったこと
        <textarea
          name="effort"
          placeholder="学校やおうちでがんばったことを教えてね"
          required
        ></textarea>
      </label>

      <label>
        今年一番うれしかったこと
        <textarea
          name="happy"
          placeholder="とても楽しかったできごとを書いてね"
          required
        ></textarea>
      </label>

      <button type="submit">サンタさんにおくる</button>
    </form>

    <p class="footer-note">送信ボタンを押すと、サンタクロースへメッセージが届きます。</p>
  </section>
</main>

// src/App.jsx
import React from "react";

const InfoBox = ({ title, children }) => (
  <div className="info-box">
    <h2>{title}</h2>
    <p>{children}</p>
  </div>
);

function App() {
  return (
    <div className="page">
      <header className="hero">
        <p className="eyebrow">Santa Claus ——— 2025</p>
        <h1>サンタさんへのおねがいフォーム</h1>
        <p className="subtitle">
          今年がんばったあなたに、サンタさんへおねがいごとをおくりましょう！
        </p>
      </header>

      <main className="content">
        <section className="form-card">
          <div className="form-header">
            <div>
              <p className="eyebrow">FORM for Japanese Kids</p>
              <h2>おねがいごとをかいてね</h2>
            </div>
          </div>

          <form
            name="santa-wish"
            method="POST"
            data-netlify="true"
            data-netlify-honeypot="secret-field"
            action="/success/"
          >
            <input type="hidden" name="form-name" value="santa-wish" />
            <p className="sr-only">
              <label>
                シークレットフィールド：
                <input name="secret-field" />
              </label>
            </p>

            <label className="field">
              <span className="label">欲しいプレゼント</span>
              <p className="note">
                サンタクロースはなんでもあげれる訳ではありません。
                <br />
                プレゼントはお父さん・お母さんと相談して、お二人が「いいよ」と言ったものを入力してください。
              </p>
              <input
                type="text"
                name="gift"
                required
                placeholder="例：漢字テスト特訓セット"
                aria-describedby="gift-note"
              />
            </label>

            <label className="field">
              <span className="label">今年がんばったこと</span>
              <textarea
                name="effort"
                rows="3"
                required
                placeholder="がんばったことをおしえてね"
              />
            </label>

            <label className="field">
              <span className="label">今年一番うれしかったこと</span>
              <textarea
                name="happy"
                rows="3"
                required
                placeholder="わくわくしたできごとをおしえてね"
              />
            </label>

            <button type="submit">サンタさんへおくる</button>
          </form>
        </section>
      </main>
    </div>
  );
}

export default App;
